Feat: implement createGroup api client and server action
genesis-tech-tribe/nishiki-frontend pull request #183
Opened 2024-01-12 08:52 UTC by kanta1207

## Overview

- Implement `createGroup` api client
- Implement `CreateGroupAction` to invoke `createGroup` in client component(`src/features/groups/components/CreateGroupButton/CreateGroupDrawerContent.tsx`)

## Changes

- Add `createGroup` method to `src/lib/api/groupApiClient.ts`
- Add html `<form>` tag to `src/features/groups/components/CreateGroupButton/CreateGroupDrawerContent.tsx`
- Invoke `createGroupAction` in `src/features/groups/components/CreateGroupButton/CreateGroupDrawerContent.tsx`

## What I didn't in this PR
**I will tackle on Implementation of `CreateGroupForm` component in next scope, using common `Form` component and react-hook-form.** 
In this PR, I only focused on the API call.

## Review points

- Is API client `createGroup` method properly implemented?
- Is server action `createGroupAction` method properly implemented?

## Note

-  

## Assignee Checklist:

- [x] The base branch is correct (See: [Types of Branches](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#types-of-branches))
- [x] The branch name follows the [Branch Naming Conventions](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/CONTRIBUTING.md#branch-naming-conventions)
- [x] The correct assignees and reviewers have been designated for this PR
- [x] The coding style follows the [Coding Style Guide](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [x] All the related issues are associated with this PR
- [x] All criteria in the associated issues are met (please tick the checkboxes)
- [x] My changes do not generate new warnings or errors (especially in the console)

## Reviewer Checklist:

- [ ] The code follows the generic best practices and our [Coding Style Guide](https://github.com/genesis-tech-tribe/nishiki-frontend/blob/develop/docs/STYLEGUIDE.md)
- [ ] Code is well-commented and easy to understand
- [ ] UI changes accurately reflect the provided design

2024-01-12 09:26 UTC, kanta1207 commented
Importing `createGroupAction' into client component causing a build error.

2024-01-23 22:01 UTC, kotaaaa approved these changes
I thought this PR's scope is a little bit small, but it's good to go. Thanks!

2024-01-23 23:14 UTC, uskayyyyy requested changes
@kanta1207 
Thank you for the implementation! Please kindly check the comments I left.

2024-01-23 23:14 UTC, uskayyyyy commented on src/features/groups/components/CreateGroupButton/CreateGroupDrawerContent.tsx
> +  const [groupName, setGroupName] = useState('');
Could you add `<IGroup['name']>`, please?
Currently, the type is inferred as a simple `string`, not referring to the type of group name.

2024-01-23 23:14 UTC, uskayyyyy commented on src/lib/api/group/client/groupApiClient.client.ts
> +  groupId: string;
`IGroup['id']`

2024-01-23 23:14 UTC, uskayyyyy commented on src/lib/api/group/client/groupApiClient.client.ts
> +  groupName: string;
`IGroup['name']`

2024-01-24 00:29 UTC, kanta1207 commented
> @kanta1207 Thank you for the implementation! Please kindly check the comments I left.

Thank you for your review! I addressed the points you brought up. Please take a relook at them 🙏

2024-01-24 00:31 UTC, uskayyyyy approved these changes
@kanta1207 
Thank you for updating! LGTM :)

2024-01-24 00:31 UTC, kanta1207 commented
> I thought this PR's scope is a little bit small, but it's good to go. Thanks!

@kotaaaa Yeah indeed maybe I tried to make it too small 😅 
I'll just replace `form` with `Form` component quickly in next PR

2024-01-24 00:32 UTC, merged